version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
        node-version: "16.13.2"
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run udagram-frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run udagram-api:install
      - run:
          name: Front-End Build
          command: |
            npm run udagram-frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run udagram-api:build
      - run:
          name: Deploy App API
          command: |
            npm run udagram-api:deploy 
      - run:
          name: Deploy App Front
          command: |
            npm run udagram-frontend:deploy